# Notebook de Limpieza

En este Notebook limpio el primer dataframe para quedarme con un listado de nombres de vehículos

In [1]:
# Importo librerias
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re
import seaborn as sns

In [2]:
# Importo el DF
df_extraccion = pd.read_csv('DF_extraccion.csv')
df_extraccion

,Nombre,Valoraciones,A favor,En contra,Opiniones,Precio,Características
0,1. Mazda CX-80,9/10,['Excelente eficiencia tanto en el PHEV como e...,['La suspensión puede sentirse algo seca en ci...,El CX-80 usa la misma plataforma y motores que...,Desde 54.668 €,NaN
1,2. Renault Espace,9/10,"['Consumo', 'Equipamiento disponible', 'Opción...","['Funcionamiento poco refinado en ocasiones', ...",El nuevo Renault Espace es ahora un SUV con un...,Desde 38.280 €,NaN
2,3. Hyundai Santa Fe,8/10,['Equipamiento y tecnología propios de coches ...,"['Precio elevado', 'Escasa autonomía eléctrica...",El Santa Fe dispone de motorizaciones híbrida ...,Desde 51.478 €,NaN
3,4. Skoda Kodiaq,8/10,"['Practicidad y espacio disponible', 'Oferta m...","['Ergonomía de algunos mandos', 'Plazas de la ...","El Skoda Kodiaq es mucho más barato que el Q7,...",Desde 40.001 €,NaN
4,5. Peugeot 5008,8/10,"['Amplio interior con 7 plazas de serie', 'Com...",['La calidad del sistema multimedia podría mej...,El Peugeot 5008 es un coche muy redondo y cohe...,Desde 34.885 €,NaN
...,...,...,...,...,...,...,...
167,Opel Combo e-life,NaN,NaN,NaN,NaN,NaN,['Disponible en dos tallas: Talla L y Talla XL...
168,Mercedes Clase T,NaN,NaN,NaN,NaN,NaN,['El Mercedes Clase T es un monovolumen compac...
169,Nissan Townstar,NaN,NaN,NaN,NaN,NaN,['El Nissan Townstar es una furgoneta ligera q...
170,Peugeot e-rifter,NaN,NaN,NaN,NaN,NaN,"['Disponible con los acabados Active Pack, All..."
171,Renault Kangoo Combi E-Tech,NaN,NaN,NaN,NaN,NaN,['El Renault Kangoo Combi E-Tech es una furgon...

In [3]:
# Voy a limpiar la columna de nombres para comprobar cuantos vehículos únicos tengo
# Empiezo quitando los números de los nombres
df_EDA = df_extraccion
df_EDA['Nombre'] = df_EDA['Nombre'].str.replace(r'\d+\.', '', regex=True)
df_EDA['Nombre'] = df_EDA['Nombre'].str.lstrip() # Elimino los espacios en blanco que haya al principio de los nombres
df_EDA['Nombre'] = df_EDA['Nombre'].str.rstrip() # Elimino los espacios en blanco que haya al final de los nombres
df_EDA['Nombre'] = df_EDA['Nombre'].str.title() # Para normalizar los nombres y que sólo tengan en mayúscula la primera letra de cada palabra
# Existen diferentes marcas de coches que se pueden escribir de varias maneras, asi que las voy a normalizar reemplazando
df_EDA['Nombre'] = df_EDA['Nombre'].str.replace('Citroën', 'Citroen', regex=True)
df_EDA['Nombre'] = df_EDA['Nombre'].str.replace('Škoda', 'Skoda', regex= True)
df_EDA['Nombre'] = df_EDA['Nombre'].str.replace('Mercedes-Benz', 'Mercedes',  regex= True)

df_EDA

,Nombre,Valoraciones,A favor,En contra,Opiniones,Precio,Características
0,Mazda Cx-80,9/10,['Excelente eficiencia tanto en el PHEV como e...,['La suspensión puede sentirse algo seca en ci...,El CX-80 usa la misma plataforma y motores que...,Desde 54.668 €,NaN
1,Renault Espace,9/10,"['Consumo', 'Equipamiento disponible', 'Opción...","['Funcionamiento poco refinado en ocasiones', ...",El nuevo Renault Espace es ahora un SUV con un...,Desde 38.280 €,NaN
2,Hyundai Santa Fe,8/10,['Equipamiento y tecnología propios de coches ...,"['Precio elevado', 'Escasa autonomía eléctrica...",El Santa Fe dispone de motorizaciones híbrida ...,Desde 51.478 €,NaN
3,Skoda Kodiaq,8/10,"['Practicidad y espacio disponible', 'Oferta m...","['Ergonomía de algunos mandos', 'Plazas de la ...","El Skoda Kodiaq es mucho más barato que el Q7,...",Desde 40.001 €,NaN
4,Peugeot 5008,8/10,"['Amplio interior con 7 plazas de serie', 'Com...",['La calidad del sistema multimedia podría mej...,El Peugeot 5008 es un coche muy redondo y cohe...,Desde 34.885 €,NaN
...,...,...,...,...,...,...,...
167,Opel Combo E-Life,NaN,NaN,NaN,NaN,NaN,['Disponible en dos tallas: Talla L y Talla XL...
168,Mercedes Clase T,NaN,NaN,NaN,NaN,NaN,['El Mercedes Clase T es un monovolumen compac...
169,Nissan Townstar,NaN,NaN,NaN,NaN,NaN,['El Nissan Townstar es una furgoneta ligera q...
170,Peugeot E-Rifter,NaN,NaN,NaN,NaN,NaN,"['Disponible con los acabados Active Pack, All..."
171,Renault Kangoo Combi E-Tech,NaN,NaN,NaN,NaN,NaN,['El Renault Kangoo Combi E-Tech es una furgon...

In [4]:
# Miro los valores unicos en la columna Nombre
lista_nombres = df_EDA['Nombre'].unique().tolist()
lista_nombres

['Mazda Cx-80',
 'Renault Espace',
 'Hyundai Santa Fe',
 'Skoda Kodiaq',
 'Peugeot 5008',
 'Volkswagen Tayron',
 'Kia Sorento',
 'Nissan X-Trail',
 'Mercedes Glb',
 'Toyota Highlander',
 'Volvo Xc90',
 'Audi Q7',
 'Mercedes Clase Glb',
 'Seat Tarraco',
 'Mitsubishi Outlander',
 'Hyundai Santa Fe Híbrido',
 'Volkswagen Tayron Híbrido',
 'Toyota Highlander Híbrido',
 'Volkswagen Tiguan Allspace',
 'Mercedes Eqb Eléctrico',
 'Range Rover',
 'Volvo Ex90 Eléctrico',
 'Kia Ev9',
 'Bmw X5',
 'Mercedes Gle',
 'Mercedes Gls',
 'Bmw X7',
 'Hongqi Ehs9',
 'Peugeot 5008 Híbrido',
 'Peugeot 5008 Eléctrico',
 'Nissan X-Trail Híbrido',
 'Ebro S800 Híbrido',
 'Skoda Kodiaq Híbrido',
 'Kgm (Ssangyong) Rexton',
 'Mazda Cx-80 Híbrido',
 'Volvo Xc90 Híbrido',
 'Dacia Jogger',
 'Peugeot Rifter',
 'Toyota Proace City Verso',
 'Volkswagen Caddy',
 'Volkswagen Touran',
 'Toyota Proace Verso',
 'Ford Tourneo Connect',
 'Lexus Lm',
 'Mercedes Clase T',
 'Fiat Ulysse',
 'Citroen C3 Aircross',
 'Land Rover Discovery Sport',
 'Swm G03F',
 'Dfsk E5',
 'Evo 7',
 'Opel Frontera',
 'Mercedes Clase V',
 'Renault Grand Scénic',
 'Dacia Lodgy',
 'Seat Alhambra',
 'Citroen Grand C4 Spacetourer',
 'Ford S-Max',
 'Opel Zafira Tourer',
 'Volkswagen Multivan',
 'Ford Tourneo Custom',
 'Mercedes Eqb 250',
 'Skoda Enyaq',
 'Hyundai Kona',
 'Kia E-Niro',
 'Citroen C3 Aircross Eléctrico',
 'Swm G05F',
 'Ford Transit Connect',
 'Dfsk Glory 580',
 'Dacia Jogger Híbrido',
 'Dfsk 600',
 'Citroen Spacetourer',
 'Citroen Holidays',
 'Hyundai Staria',
 'Opel Zafira',
 'Peugeot Traveller',
 'Volkswagen California',
 'Volkswagen Caravelle',
 'Citroen Ë-Berlingo',
 'Opel Combo E-Life',
 'Nissan Townstar',
 'Peugeot E-Rifter',
 'Renault Kangoo Combi E-Tech']

In [5]:
df_EDA['Nombre'].nunique()

83

In [6]:
# Los ordeno alfabeticamente
nombres = sorted(lista_nombres)
nombres

['Audi Q7',
 'Bmw X5',
 'Bmw X7',
 'Citroen C3 Aircross',
 'Citroen C3 Aircross Eléctrico',
 'Citroen Grand C4 Spacetourer',
 'Citroen Holidays',
 'Citroen Spacetourer',
 'Citroen Ë-Berlingo',
 'Dacia Jogger',
 'Dacia Jogger Híbrido',
 'Dacia Lodgy',
 'Dfsk 600',
 'Dfsk E5',
 'Dfsk Glory 580',
 'Ebro S800 Híbrido',
 'Evo 7',
 'Fiat Ulysse',
 'Ford S-Max',
 'Ford Tourneo Connect',
 'Ford Tourneo Custom',
 'Ford Transit Connect',
 'Hongqi Ehs9',
 'Hyundai Kona',
 'Hyundai Santa Fe',
 'Hyundai Santa Fe Híbrido',
 'Hyundai Staria',
 'Kgm (Ssangyong) Rexton',
 'Kia E-Niro',
 'Kia Ev9',
 'Kia Sorento',
 'Land Rover Discovery Sport',
 'Lexus Lm',
 'Mazda Cx-80',
 'Mazda Cx-80 Híbrido',
 'Mercedes Clase Glb',
 'Mercedes Clase T',
 'Mercedes Clase V',
 'Mercedes Eqb 250',
 'Mercedes Eqb Eléctrico',
 'Mercedes Glb',
 'Mercedes Gle',
 'Mercedes Gls',
 'Mitsubishi Outlander',
 'Nissan Townstar',
 'Nissan X-Trail',
 'Nissan X-Trail Híbrido',
 'Opel Combo E-Life',
 'Opel Frontera',
 'Opel Zafira',
 'Opel Zafira Tourer',
 'Peugeot 5008',
 'Peugeot 5008 Eléctrico',
 'Peugeot 5008 Híbrido',
 'Peugeot E-Rifter',
 'Peugeot Rifter',
 'Peugeot Traveller',
 'Range Rover',
 'Renault Espace',
 'Renault Grand Scénic',
 'Renault Kangoo Combi E-Tech',
 'Seat Alhambra',
 'Seat Tarraco',
 'Skoda Enyaq',
 'Skoda Kodiaq',
 'Skoda Kodiaq Híbrido',
 'Swm G03F',
 'Swm G05F',
 'Toyota Highlander',
 'Toyota Highlander Híbrido',
 'Toyota Proace City Verso',
 'Toyota Proace Verso',
 'Volkswagen Caddy',
 'Volkswagen California',
 'Volkswagen Caravelle',
 'Volkswagen Multivan',
 'Volkswagen Tayron',
 'Volkswagen Tayron Híbrido',
 'Volkswagen Tiguan Allspace',
 'Volkswagen Touran',
 'Volvo Ex90 Eléctrico',
 'Volvo Xc90',
 'Volvo Xc90 Híbrido']